[package]
name = "risp"
version = "0.7.0"
description = "A rusty Lisp inspired by Clojure for usage as simple configuration language"
repository = "https://github.com/shybyte/risp"
license = "MIT"
authors = ["shybyte@gmail.com"]

[dependencies]
regex = "^0.2"
lazy_static = "^0.2"